import Header from '@/components/Header'
import '@/globals.css'
import type { Metadata } from 'next'
import { Black_Ops_One } from 'next/font/google' // 字型

const blackOpsOne = Black_Ops_One({ weight: ['400'], subsets: ['latin'] })

const metadata: Metadata = {
  title: 'React Next Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={blackOpsOne.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
