import '@/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google' // 字型

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'React Next Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div>Header</div>
        {children}</body>
    </html>
  )
}
